spring:
  datasource:
    url: jdbc:sqlserver://myazuredbdemo.database.windows.net:1433;database=sbcurdazuredemodb;user=myazuredbdemo@myazuredbdemo;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: myazuredbdemo
    password: Azure@db2022
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191